name: profesores2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  curved_navigation_bar: ^1.0.5
  flutter:
    sdk: flutter
  get: ^4.6.6
  url_launcher: ^6.3.0
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:

    - assets/instructor.png
    - assets/libro.png
    - assets/tablero.png
    - assets/ideas.png
    - assets/final.png
    - assets/barras.png
    - assets/word.png
    - assets/exel.png
    - assets/powerpoint.png
    - assets/maestro.png
    - assets/mujer.png
    - assets/quiz.png
